# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-14 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalanSentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='classifiedCorrectly',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='polarity',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')], default=1),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(max_length=140),
        ),
    ]
